name: Deploy to FTP Server

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    # Only run if the tests workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP version (replace '8.0' with your desired PHP version)
      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Specify your version here
          extensions: mbstring, bcmath, zip, xml, curl  # Add any extensions your app needs

      - name: Create .env for SQLite
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env

      # Install PHP dependencies (Composer)
      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}/
          exclude: |
            **/node_modules/**
            .env
            .env.example
            tests/**
            phpunit.xml
